# Minh Quang Hoang - Cao Minh Nguyen
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  install:
    docker:
      - image: cimg/node:16.16.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    docker:
      - image: cimg/node:16.16.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:16.16.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn test
        
      - store_test_results:
          path: ~/test-results
          
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      # - image: cimg/node:16.16.0
      - image: "cimg/python:3.7"
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: build
          to: "s3://react-cicd-demo-app-mquang-cminh/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  ci-wf:
    jobs:
      # - install
      # - test:
      #     requires:
      #       - install
      # - build:
      #     requires:
      #       - test
      # - deploy:
      #     requires:
      #       - build

      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
