# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
orbs: 
  react: thefrontside/react@0.2.0

version: 2.1

workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
